import os

from pages.base import WebPage
from pages.elements import WebElement
from pages.elements import ManyWebElements

class Pages(WebPage):

    def __init__(self, web_driver, url=''):
        if not url:
            url = os.getenv("MAIN_URL") or 'https://www.labirint.ru/'

        super().__init__(web_driver, url)

    search = WebElement(id='search-field')
    search_run_button = WebElement(xpath='//button[@class="b-header-b-search-e-btn"]')
    message_search = WebElement(xpath='//h1[@class="index-top-title"]')
    message_result = WebElement(xpath='//*[@id="search"]/div[1]/h1')
    book_button = WebElement(xpath='//a[@class="b-header-b-menu-e-text" and contains(text(), "Книги")]')
    best_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[4]/div/div[1]/ul/li[2]/span/a')
    school_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[4]/div/div[1]/ul/li[3]/span/a')
    toys_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[4]/div/div[1]/ul/li[4]/span/a')
    office_supplies_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[4]/div/div[1]/ul/li[5]/span/a')
    message_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[2]/div/ul/li[3]/a/span[2]')
    my_labirint_button = WebElement(
        xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[2]/div/ul/li[4]/a/span[2]/span[1]/span')
    postponed_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[2]/div/ul/li[5]/a/span[2]')
    basket_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[2]/div/ul/li[6]/a/span[2]')
    delivery_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[2]/div/ul/li[1]/a')
    certificate_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[2]/div/ul/li[2]/a')
    rating_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[2]/div/ul/li[3]/a')
    novelty_button = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div[2]/div/ul/li[4]/a')
    sale_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[2]/div/ul/li[5]/a')
    contact_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[2]/div/ul/li[9]/a')
    support_button = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[2]/div/ul/li[10]/a')
    region_button = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div[1]/div[4]/div/div[1]/ul/li[12]/span[1]/span/span[3]/span')
    field_region_button = WebElement(xpath='//*[@id="region-post"]')
    click_region = WebElement(xpath='//*[@id="ui-id-5"]/a')
    message_region = WebElement(xpath='//span[@title="Красноярск"]')
    maps_button = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div[1]/div[4]/div/div[1]/ul/li[12]/span[2]/span[2]/a')
    search_result = WebElement(xpath='//*[@id="stab-slider-frame"]/ul/li[1]/a/span[2]')
    link_youtube = WebElement(xpath='//a[@data-event-content="Ютьюб"]')
    link_VK = WebElement(xpath='//a[@data-event-content="ВКонтакте"]')
    link_VK_kids = WebElement(xpath='//a[@data-event-content="ВКонтакте. Дети"]')
    link_classmates = WebElement(xpath='//a[@data-event-content="Одноклассники"]')
    link_zen = WebElement(xpath='//a[@data-event-content="Дзен"]')
    link_t_me = WebElement(xpath='//a[@data-event-content="Телеграм"]')
    link_tiktok = WebElement(xpath='//a[@data-event-content="ТикТок"]')
    social_button = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div[2]/div/div/div/a[1]/em')
    button_still = WebElement(xpath='//*[@id="minwidth"]/div[6]/div/div[1]/div[4]/div/div[1]/ul/li[10]/span/span[1]')
    button_multimedia = WebElement(xpath='//*[@id="body-top"]/div[4]/div[2]/div/div[2]/div[1]/div[2]/ul/li[6]/a')
    button_souvenir = WebElement(xpath='//*[@id="body-top"]/div[4]/div[2]/div/div[2]/div[1]/div[2]/ul/li[7]/a')
    button_home_goods = WebElement(xpath='//a[@class="b-rfooter-e-item-link" and contains(text(), "Товары для дома")]')
    button_club = WebElement(xpath='//a[data-event-content="Клуб"]')
    what_reed_button = WebElement(xpath='//*[@id="right-inner"]/div[1]/div[1]/a')
    what_reed_recommend = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div[1]/div[1]/div/a[2]/span[2]/span/span')
    child_nav_button = WebElement(xpath='//*[@id="minwidth"]/div[4]/div/div/div/ul/li[3]/a')
    button_journals = WebElement(xpath='//*[@id="minwidth"]/div[4]/div/div/div/ul/li[4]/a')
    button_review = WebElement(xpath='//*[@id="minwidth"]/div[4]/div/div/div/ul/li[5]/a')
    button_reader = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div/div/ul/li[6]/a')
    button_recommendations = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div/div/ul/li[7]/a')
    button_littest = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div/div/ul/li[8]/a')
    button_contests = WebElement(xpath='//*[@id="minwidth"]/div[5]/div/div/div/ul/li[9]/a')
    link_appstore = WebElement(xpath='//*[@id="body-top"]/div[4]/div[2]/div/div[1]/div[1]/div[2]/a[1]')
    link_appgallery = WebElement(xpath='//*[@id="body-top"]/div[4]/div[2]/div/div[1]/div[1]/div[2]/a[3]')
    link_google_play = WebElement(xpath='//*[@id="body-top"]/div[4]/div[2]/div/div[1]/div[1]/div[2]/a[2]')
    button_soap = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[1]/a')
    button_toothpaste = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[2]/a')
    button_wipes = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[3]/a')
    button_calendars = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[1]/a')
    button_cal_advent = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[1]/a')
    button_cal_magnet = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[2]/a')
    button_kvartal_cal = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[3]/a')
    button_wall_cal = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[4]/a')
    button_small_cal = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[5]/a')
    button_audio = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[1]/a')
    button_video = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[2]/a')
    button_soft = WebElement(xpath='//*[@id="minwidth"]/div[5]/div[1]/div[2]/div/div[3]/ul/li[3]/a')
    button_action = WebElement(xpath='//*[@id="body-top"]/div[5]/div[2]/div/div[2]/div[2]/div[2]/ul/li[1]/a')
